name: Deploy

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, DiscordBot]

    steps:
      - name: Deploy Discord bot
        run: |
          cd /opt/DiscordBot
          git fetch origin testing
          git switch testing
          git pull --ff-only origin testing
          docker compose up -d --build
          docker image prune -f
